### ISSUE TITLE
Make release notes discoverable for Renovate

### ISSUE THREAD

**Issue by setchy** [apollographql/federation-jvm#107]
We use Renovate Bot to keep our application dependencies up-to-date.  Overnight our bot detected the new 0.6.4 release, but it wasn't able to pull in any detailed release notes.

My understanding is renovate can pull from a few places, one being a `CHANGELOG.md` at the root of the repository.  `apollo-server` is an example repository which correctly pulls in the change / release notes from its [CHANGELOG.md](https://github.com/apollographql/apollo-server/blob/main/CHANGELOG.md)

I raised a similar ticket a few weeks back for the federation libraries - see https://github.com/apollographql/federation/issues/636.

**Comment by martinbonnin** [comment]
Hi @setchy 👋 ! The release notes are in [RELEASE_NOTES.md](https://github.com/apollographql/federation-jvm/blob/master/RELEASE_NOTES.md). 

If I understand correctly, renovate [uses](https://github.com/renovatebot/renovate/blob/5273cbc1cbdafdc1d6aae0ee38c7c53685f066d2/lib/workers/pr/changelog/github/index.ts#L1) [changelog-filename-regex](https://github.com/shinnn/changelog-filename-regex), which itself should detect `RELEASE_NOTES.md` [correctly](https://runkit.com/embed/ruyzpdlfmmux).

So it should all work ? Or am I missing something ?

**Comment by setchy** [comment]
Hi @martijnwalraven, you're correct - I think at the time of posting the original issue it was not working as expected.  

However I can confirm with the latest renovate v27.19.1 that its working again - so we can close this ticket

Example below 
<img width="939" alt="renovate-federation-jvm" src="https://user-images.githubusercontent.com/386277/134769269-a1801281-de09-4f91-a3c3-21e4bdb19f54.png">

That said, it would be nice if an excerpt of the [RELEASE_NOTES.md](https://github.com/apollographql/federation-jvm/blob/master/RELEASE_NOTES.md) were additionally added to the [github release tags ](https://github.com/apollographql/federation-jvm/blob/master/RELEASE_NOTES.md).  It's typically my first go-to for a quick summary

**Comment by setchy** [comment]
Though this renovate bug still seems to be lingering https://github.com/renovatebot/renovate/issues/10955

**Comment by martinbonnin** [comment]
> That said, it would be nice if an excerpt of the RELEASE_NOTES.md were additionally added to the github release tags . It's typically my first go-to for a quick summary

I usually go to tags as well but I'm not a fan of duplicating the release notes in both tags and RELEASE_NOTES.md. It happens that we need to tweak the release notes sometimes and having to do it in 2 places is a recipe for discrepancies. One advantage of RELEASE_NOTES.md is that it's a searchable 1-page document so if you're looking for graphql-java support, you can search "17" and lookup the version relatively easily. I'm not sure if there are best practices around this yet? If not, I'd keep it this way for now.

**Comment by setchy** [comment]
Makes perfect sense @martijnwalraven - i tend to agree.

I did find a few projects that can keep the tags sync'd with changelog.md (eg: https://github.com/dropseed/changerelease), but I cannot vouch for them first hand.

For now, I'm closing this as the original issue now seems to be resolved

**Comment by martinbonnin** [comment]
Sounds good 👍 
PS: I think you have the wrong Marti(j)n. Martijn is more "federation-Martijn" and i'm more "jvm-Martin" :)

**Comment by setchy** [comment]
🤦 😅
