### ISSUE TITLE
Query on using Gateway

### ISSUE THREAD

**Issue by JonathanGladwin** [apollographql/federation-jvm#110]
Hi,

Thanks for this project.

Are you using Apollo Gateway for gateway implementation? Does Federation-jvm act as gateway instead apollo gateway?
We want to use Java for Gateway or server implementation instead of using Node. Can you suggest us how to do this?

Thanks,

**Comment by sachindshinde** [comment]
Thanks for your interest in the project!

>Are you using Apollo Gateway for gateway implementation?

Indeed, this project is for use in conjunction with Apollo Gateway.

>Does Federation-jvm act as gateway instead apollo gateway?

The `federation-jvm` does not act as a gateway, but instead lets an implementing service written in `graphql-java` be used with Apollo Gateway.

>We want to use Java for Gateway or server implementation instead of using Node. Can you suggest us how to do this?

We do not have a Java version of Apollo Gateway at this time. If you'd like to write a Java server/implementing service, you can do so with `graphql-java` and use this library to transform your schema into one that's compliant with the federation programming model (meaning it can be used with Apollo Gateway).
