### ISSUE TITLE
Federation-jvm is Gateway?

### ISSUE THREAD

**Issue by JonathanGladwin** [apollographql/federation-jvm#111]
Hi Team,
Need your advise urgently. I need to use dgs-federation example (pls refer below url), but i need to java based gateway (not the apollo gateway which is node based)
https://github.com/Netflix/dgs-federation-example

Is your Federation-jvm acts as Gateway? Can i replace in the above dgs example in place of apollo gateway?

Appreciate your help.

**Comment by sachindshinde** [comment]
>Is your Federation-jvm acts as Gateway? Can i replace in the above dgs example in place of apollo gateway?

The `federation-jvm` project is not a gateway, so it cannot replace Apollo Gateway in the above example.
