### ISSUE TITLE
Support for graphql-java version 17.+

### ISSUE THREAD

**Issue by golfingal72** [apollographql/federation-jvm#126]
Can you please make a release that is compatible with graphql-java/graphql-java version 17.+
There are some breaking changes to the 
graphql-java-support/src/main/java/com/apollographql/federation/graphqljava/FederationSdlPrinter.java

because the Directive GraphQLArgument object has changed, but the fixes can be found easily at:

https://github.com/graphql-java/graphql-java/blob/b525ada641bade0ea509669b28cb1920b33a2709/src/main/java/graphql/schema/idl/SchemaPrinter.java

since it appears this is basically a copy of that code to begin with.  

The only other thing that failed was bootstrapping some of the spring tests which I did not spend the time to decode.  

The new version of graphql has performance improvements that seem worthwhile.  I am using Netflix DGS framework and in order for them to upgrade, there has to be a version of this library working with graphql-java V 17.+

**Comment by martinbonnin** [comment]
Closed with https://github.com/apollographql/federation-jvm/pull/129 that update graphql-java to 17.3. It's available in version `0.7.0`. Let us know how that works!
