### ISSUE TITLE
Add support for composing a federated graph. 

### ISSUE THREAD

**Issue by patrickdronk** [apollographql/federation-jvm#139]
I might be missing it, but is composing graphs to a gateway graph on the roadmap?

**Comment by martinbonnin** [comment]
Hi 👋 Can you share more details about your use case? Are you looking for something like [Apollo Router](https://github.com/apollographql/router) but for the JVM? Or something else?

**Comment by patrickdronk** [comment]
I'm sorry, I should've given more context. 
I wanted to build a simple schema registry, with a validation step for composing a supergraph. 
The typescript `@apollo/federation` package has the composeAndValidate function. I was hoping this jvm had it as well. But I couldn't find it.

**Comment by martinbonnin** [comment]
Thanks for the context! Indeed, you're right. There's no composition code in `federation-jvm`. I updated the title of this issue to keep track of the feature request.
