### ISSUE TITLE
Federation 2 support

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/federation-jvm#143]
After discussion with @BoD and @pcmanus, the initial step is to add [definitions for `@link` and `@shareable` ](https://gist.github.com/pcmanus/46a9f81b9edb4768e6f322b3242dc9b1) in the returned schema. 

Support for directives rename is out of scope at the moment

**Comment by hwillson** [comment]
This was completed in https://github.com/apollographql/federation-jvm/pull/144 🎉
