### ISSUE TITLE
union not working with federation-jvm

### ISSUE THREAD

**Issue by MariuszCwikla** [apollographql/federation-jvm#154]
`Federation.transform()` fails with below error if there is union type defined in schema:

```
Caused by: graphql.schema.idl.errors.SchemaProblem: errors=[There is no type resolver defined for interface / union 'ProductResult' type]
```

e.g. with following schema

```
type Mutation{
	createProduct(symbol: String!): ProductResult
}

type Product{
	symbol: String!
}
type ProductError{
	reason: String
}
union ProductResult = Product | ProductError 
```

I have prepared a repository to demonstrate the issue https://github.com/MariuszCwikla/spring-graphql-federation-union-issue.

If you disable federation, e.g. by commenting out this bean:
```
//@Configuration   //comment this out
public class SpringGraphqlFedrationConfiguration {
```
then application runs fine.

I am not sure yet if this is `federation-jvm` issue or Spring GraphQL but after some debugging I found that issue might be inside this method:

```
  private static RuntimeWiring.Builder copyRuntimeWiring(RuntimeWiring runtimeWiring) {
    // Annoyingly graphql-java doesn't have a copy constructor for RuntimeWiring.Builder.
    RuntimeWiring.Builder builder = RuntimeWiring.newRuntimeWiring();

    runtimeWiring.getDataFetchers().entrySet().stream()
        .map(
            entry -> {
              String name = entry.getKey();
              TypeRuntimeWiring.Builder typeWiring = TypeRuntimeWiring.newTypeWiring(name);
              typeWiring.dataFetchers(entry.getValue());
              if (runtimeWiring.getDefaultDataFetcherForType(name) != null) {
                typeWiring.defaultDataFetcher(runtimeWiring.getDefaultDataFetcherForType(name));
              }
              if (runtimeWiring.getTypeResolvers().get(name) != null) {
                typeWiring.typeResolver(runtimeWiring.getTypeResolvers().get(name));
              }
```

`RuntimeWiring` passed to the method has a type resolver for `ProductResult`. Above method according to the comment is trying to make a copy of if. When method is finished resulting object does not have such type resolver any more.

**Comment by BoD** [comment]
Thank you so much for the detailed bug report with analysis + repro project!  🙏 Version `2.0.0-alpha.3` should be available in a moment, and should resolve the issue.
