### ISSUE TITLE
Spotless fails on Java 16+ 

### ISSUE THREAD

**Issue by martinbonnin** [apollographql/federation-jvm#169]
Follow up from https://github.com/diffplug/spotless/issues/834. 

There's a lot of information in https://github.com/apollographql/federation-jvm/issues/167 about a possible workaround.

**Comment by dariuszkuc** [comment]
Resolved in https://github.com/apollographql/federation-jvm/pull/209

**Comment by dariuszkuc** [comment]
Still an issue.

**Comment by dariuszkuc** [comment]
Resolved in https://github.com/apollographql/federation-jvm/pull/210
