### ISSUE TITLE
Project cleanup (Fed JVM is an officially supported Apollo OSS project)

### ISSUE THREAD

**Issue by hwillson** [apollographql/federation-jvm#173]
This project has had an interesting history; it was originally created to address Apollo's own specific infrastructure needs, but has since grown into a reliable and effective way to work with Federation 1/2 on a JVM. While the library itself has grown, the supporting OSS infrastructure for this project has not, since this project was not staffed as an official Apollo OSS project. This has changed, meaning Federation JVM now has a team behind it. To reflect this, we need to make several changes to this project and repo to bring it up to Apollo OSS standards. We'll use this issue to track the needed changes at a high level, breaking more specific todos out into separate issues.

Things that need to happen:

- [x] #178
- [x] #179
- [x] #180
- [ ] #181
- [x] #182
- [ ] Public API tracking with [japicmp](https://siom79.github.io/japicmp/)? (or something else?)
- [ ] Agree on codestyle
- [ ] Improve test coverage and functionality
- [ ] Add ROADMAP.md
- [x] Drop `RELEASE_NOTES.md` in favor of using Github Release

**Comment by setchy** [comment]
+ `CHANGELOG.md` and `ROADMAP.md` please 🙏

**Comment by martinbonnin** [comment]
+1 for `ROADMAP.md` 👍 

For `CHANGELOG.md`, there is [RELEASE_NOTES.md](https://github.com/apollographql/federation-jvm/blob/master/RELEASE_NOTES.md), did you want to change the name (I remember something about renovate maybe? 👀 ) ? Or more details in there?

**Comment by setchy** [comment]
Ah, my bad @martinbonnin - I overlooked RELEASE_NOTES.md.  Renovate can handle , but perhaps a rename to make it consistent with apollographql/federation, apollographql/apollo-server, apollographql/rover etc wouldn't hurt

**Comment by martinbonnin** [comment]
> a rename to make it consistent with apollographql/federation, apollographql/apollo-server, apollographql/rover etc wouldn't hurt

Works for me 👍

**Comment by dariuszkuc** [comment]
Instead of using separate `RELEASE_NOTES.md`/`CHANGELOG.md` files we will be using standard Github Releases as it will contain the same information.

**Comment by setchy** [comment]
Yes, huge thank you @dariuszkuc 👏
