### ISSUE TITLE
Example(s) that show how to use Federation JVM

### ISSUE THREAD

**Issue by dariuszkuc** [apollographql/federation-jvm#182]
Create example apps that show how to use Federation JVM with popular libraries/frameworks.

Examples:
- [x] `spring-graphql` - [official Spring project](https://docs.spring.io/spring-graphql/docs/current/reference/html/)
- [x] `dgs-framework` - [The DGS Framework](https://netflix.github.io/dgs/) (Domain Graph Service) is a GraphQL server framework for Spring Boot, developed by Netflix.
- [x] `graphql-java-kickstart`

**Comment by setchy** [comment]
Awesome!

I had previously raised the topic about the relationship between:

- [spring-example](https://github.com/apollographql/federation-jvm/tree/master/spring-example) within this repo (with two profiles)
- external samples (ie: [dgs-federation-example](https://github.com/Netflix/dgs-federation-example) or [spring-boot-federation-example](https://github.com/setchy/spring-boot-federation-example))
- [apollo-federation-subgraph-compatibility](https://github.com/apollographql/apollo-federation-subgraph-compatibility) implementations ([dgs](https://github.com/apollographql/apollo-federation-subgraph-compatibility/tree/main/implementations/dgs), [kickstart](https://github.com/apollographql/apollo-federation-subgraph-compatibility/tree/main/implementations/federation-jvm)

Wondering if there is an opportunity to simplify and/or reference in the updated documentation

**Comment by dariuszkuc** [comment]
Following the linked DGS and GraphQL Java Kickstart examples, I created separate https://github.com/apollographql/federation-jvm-spring-example repository as well. We will be dropping example subprojects from this repository.

**Comment by dariuszkuc** [comment]
👋 good callout! I've opened some issues in the https://github.com/apollographql/federation-jvm-spring-example repo to track adding additional use cases.
