### ISSUE TITLE
Protobuf-java version is not correct in Maven Library for 2.X

### ISSUE THREAD

**Issue by NorthernMystic** [apollographql/federation-jvm#235]
we are recently trying to migrate from Apollo federation v1 to federation v2.
To upgrade the schema to v2 in our subgraph service, we upgraded the **federation-graphql-java-support** library from 0.5.0 to 2.X.
Then all Graphql requests time out with issue: [org.springframework.web.context.request.async.AsyncRequestTimeoutException]
After debugging, we found the library imported from the maven repository still using the legacy Protobuf-java, which is mismatched with the one mentioned in the release note.
The exception is thrown in CompletableFuture.uniWhenCompleteStage: 
`java.lang.NoSuchMethodError: com.google.protobuf.GeneratedMessageV3.isStringEmpty(Ljava/lang/Object;)`
![Screen Shot 2022-08-01 at 4 30 21 PM](https://user-images.githubusercontent.com/31714103/182262497-3be3fba3-b7f8-48c7-8707-a62e50fd439e.png)
![Screen Shot 2022-08-01 at 4 30 35 PM](https://user-images.githubusercontent.com/31714103/182262496-8a5d72bf-25d3-466a-a0fa-059751d913af.png)
We must manually import the right protobuf-java version to make the application work.

**Comment by dariuszkuc** [comment]
Hello 👋 
It appears to be a Maven issue with your project setup - verify whether you import a BOM that specifies the old version or some other library transitively picks it up. Maven is rather crude with its dependency resolution strategy and uses shortest-path algorithm to select the first one it encounters (if path depth is the same then its picked in the the order they are defined in the pom file) so given something like

```
- foo-dependency
  |- bar-dependency v0.0.1
- baz-dependency
  |- bar-dependency v1.0.0
```

Maven will pick up the transitive dependency of `foo-dependency` even though `baz-dependency` uses new version.

You can use `dependency:tree` goal to check out the resolution. See https://maven.apache.org/plugins/maven-dependency-plugin/examples/filtering-the-dependency-tree.html (use `verbose` option to get full tree).

**Comment by NorthernMystic** [comment]
Hey, @dariuszkuc Thanks for the quick reply.
the result of maven dependency tree:

[INFO] +- com.apollographql.federation:federation-graphql-java-support:jar:2.0.4:compile
[INFO] |  +- com.apollographql.federation:federation-graphql-java-support-api:jar:2.0.4:compile
[INFO] |  +- com.graphql-java:graphql-java:jar:19.0:compile
[INFO] |  |  +- com.graphql-java:java-dataloader:jar:3.2.0:compile
[INFO] |  |  |  \- (org.slf4j:slf4j-api:jar:1.7.30:compile - version managed from 1.7.36; omitted for duplicate)
[INFO] |  |  +- org.reactivestreams:reactive-streams:jar:1.0.3:compile (version managed from 1.0.2)
[INFO] |  |  \- (org.slf4j:slf4j-api:jar:1.7.30:compile - version managed from 1.7.35; scope updated from runtime; omitted for duplicate)
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.30:compile
[INFO] |  \- com.google.protobuf:protobuf-java:jar:3.14.0:compile (version managed from 3.21.4)

After checking the maven docs, I suppose we need to put the import dependency under the dependencyManagement part.
Will close this issue as it is resolved.
