### ISSUE TITLE
_entities error

### ISSUE THREAD

**Issue by elineback** [apollographql/federation-jvm#256]
I am seeing this error when I try to directly hit my federated app directly with a gateway query and I am wondering how I might fix it?
![Screen Shot 2022-10-20 at 5 11 57 PM](https://user-images.githubusercontent.com/8008084/197076545-430861aa-4a5b-4b79-8890-518a8ea5f742.png)

**Comment by dariuszkuc** [comment]
It appears that the server library you are using (or your entities resolver) responds with null value instead of an array with null value inside.

**Comment by elineback** [comment]
[demo-fed.zip](https://github.com/apollographql/federation-jvm/files/9834559/demo-fed.zip)
I made this super tiny app to replicate the issue. Not sure what you mean by server library? It is running on tomcat.

**Comment by elineback** [comment]
query
query($representations:[_Any!]!){
  _entities(representations:$representations){
    ...on CcrcRecogConfig{configName}
  }
}

**Comment by elineback** [comment]
{
	"representations": [
		{
			"__typename": "CcrcRecogConfig",
			"recogConfigUuid": "18f513c3-29b2-43e0-bfad-912e16facc86"
		}
	]
}

**Comment by elineback** [comment]
Do I need to add some custom entity to this bean?
  @Bean
  public GraphQlSourceBuilderCustomizer federationTransform() {
    return builder -> {
      builder.schemaFactory((registry, wiring)->
        Federation.transform(registry, wiring)
          .fetchEntities(env -> null)
          .resolveEntityType(env -> null)
          .build()
      );
    };
  }

**Comment by dariuszkuc** [comment]
> Do I need to add some custom entity to this bean?

Yes. You need to implement entity union type resolver (so server knows which object it is returning) and entities field data fetcher (it creates entities based on the passed in representation).

In your code above both type resolver and data fetcher are just returning null.

**Comment by elineback** [comment]
Ah ok. Thanks! Do you know if there are any examples of this I could look at?

**Comment by dariuszkuc** [comment]
See https://github.com/apollographql/federation-jvm#usage

**Comment by elineback** [comment]
Thanks again.
