### ISSUE TITLE
Add support for Federation v2.3 spec

### ISSUE THREAD

**Issue by moonflare** [apollographql/federation-jvm#277]
### Context
In the next version ([v2.3](https://github.com/apollographql/federation/blob/main/gateway-js/CHANGELOG.md#230)) of the Gateway, will be added support for the [v2.3 spec](https://github.com/apollographql/federation/blob/main/subgraph-js/CHANGELOG.md#230), together with a new directive, `@interfaceObject`. You can read more about it [here](https://github.com/apollographql/federation/issues/2277).

### Problem
Currently, we can't use the `@interfaceObject` directive, at it is only supported in the `v2.3` spec. When using the `v2.3` spec, we get the [exception](https://github.com/apollographql/federation-jvm/blob/8d66f731b9bab4d89d67a9d5b53a08182b4c1fa1/graphql-java-support/src/main/java/com/apollographql/federation/graphqljava/FederationDirectives.java#L205) below

> com.apollographql.federation.graphqljava.exceptions.UnsupportedFederationVersionException: Specified federation spec = https://specs.apollo.dev/federation/v2.3 is currently not supported

### Proposed solution
To allow the usage of the `v2.3` federation spec, we could extend the functionality [here](https://github.com/apollographql/federation-jvm/blob/8d66f731b9bab4d89d67a9d5b53a08182b4c1fa1/graphql-java-support/src/main/java/com/apollographql/federation/graphqljava/FederationDirectives.java#L198) to load definitions for `v2.3` as well. To keep it consistent, we _could_ add the definitions for `v2.2` as well.

I'm planning on opening a PR with the extended functionality, but I might need a hand to make sure everything is covered.

**Comment by dariuszkuc** [comment]
Hello 👋 
Just released [2.3.0-alpha.0](https://github.com/apollographql/federation-jvm/releases/tag/v2.3.0_alpha.0).

Will release final `v2.3.0` once the Federation Spec goes GA.

**Comment by moonflare** [comment]
Thanks for the quick response @dariuszkuc 🙌🏻 

This alpha version will help test the `v2.3` spec, so thanks a lot for the release.

Before you release the final version of the `v2.3.0` spec support, I would love to address some cases introduced by the new spec around the `@interfaceObject` directive/functionality. I already started working on a PR to addressing those, but will make sure to describe those here first and get some feedback before going any forward. Let me get back these days with some detailed cases we might need to cover in the final version.

**Comment by dariuszkuc** [comment]
Hello 👋 

>There is an explicit error when we use @key on an interface, but the spec is not v2.3+. Do you think you might be worth covering that as well? [Here](https://github.com/apollographql/federation/pull/2279/files#diff-b1fed99113813ea67905b0212fe42e1255e04c152df516f0acf92c7466f721deR62) is the error I'm mentioning. Currently, we can use @key on interfaces, even on specs lower than v2.3.

While the `@key` definition specified both `OBJECT | INTERFACE` as valid locations, it never actually worked. I believe composition would just ignore (or drop?) whatever was on the interface. Since it was ignored, implementing types could define completely different `@key`s or omit them altogether.

Therefore I think having an explicit error when using old fed versions makes more sense - i.e. otherwise end users might think that this feature works whereas it never did -> it is a user error. If this behavior is problematic we can probably change it to a warning message.
