### ISSUE TITLE
Getting Argument value on a child resolver.

### ISSUE THREAD

**Issue by yuhanz** [apollographql/federation-jvm#36]
The method `dataFetchingEnvironment.getArgument(name)` always gives values, regardless whether the value is hardcoded in the query, or passed through a graphql variable reference.

However, to get the argument value on a child resolver, it may return a `VariableReference` object than a plain value (in class `IntValue` for example). The .name field on the `VariableReference` can be used as a key on `dataFetchingEnvironment.variables` to get the value. This snippet roughly demonstrates the process: 

```
    private Integer get(DataFetchingEnvironment dataFetchingEnvironment) {
        List<Selection> selections = dataFetchingEnvironment.getField().getSelectionSet().getSelections();
        VariableReference ref = (VariableReference) ((Field)selections.get(0)).getArguments().get(0).getValue();
        return (Integer) dataFetchingEnvironment.getVariables().get(ref.getName());
```

So I have been using custom logic to get argument value from the resolver at the child nodes. But we prefer to use something provided by the library so that the `dataFetchingEnvironment.variables` is transparent to the developers.

Is there a simpler way provided by the library that already achieves this?

**Comment by pcarrier** [comment]
@yuhanz This question is best suited for [the larger graphql-java community](https://www.graphql-java.com/contact/) as it doesn't relate to Apollo Federation. See you on Spectrum?
