### ISSUE TITLE
generateServiceSDL in ServiceSDLPrinter - invalid includeDirectives configfuration?

### ISSUE THREAD

**Issue by Przemeo** [apollographql/federation-jvm#361]
Hello,
I am using _Federation.transform(GraphQLSchema schema)_ method (which creates _SchemaTransformer_) and finally building the schema using _SchemaTransformer.build()_ method - I have noticed that the _sdl_ it generates does not include my own directives when _isFederation2_ is set to false.
I think the problem occurs because _generateServiceSDL_ method in _ServiceSDLPrinter_ sets _includeDirectives_ as _FederationDirectives.allNames::contains_ - shouldn't the negated predicate be used here?

**Comment by dariuszkuc** [comment]
Hello 👋 
SDL generated for Federation v1 schemas is not a full schema but rather a schema that should be used for composition (and returned as part of the `_service { sdl }` query). Federation v2 relaxed composition rules to accept full SDL schemas.

I'd highly recommend to migrate to Federation v2 ASAP.
