### ISSUE TITLE
Federation 2.6 support

### ISSUE THREAD

**Issue by RoKKim** [apollographql/federation-jvm#374]
Currently, when using "https://specs.apollo.dev/federation/v2.6" and calling `com.apollographql.federation.graphqljava.directives.LinkDirectiveProcessor#loadFederationImportedDefinitions`, the following exception is returned:
```java
com.apollographql.federation.graphqljava.exceptions.UnsupportedFederationVersionException: Specified federation spec = https://specs.apollo.dev/federation/v2.6 is currently not supported
```
Are there any plans to add support for Federation 2.6?

**Comment by melo0187** [comment]
Apparently they added it with today's release 4.4.0: https://github.com/apollographql/federation-jvm/releases/tag/v4.4.0
