### ISSUE TITLE
Update usage snippet in spring-subscription-callback

### ISSUE THREAD

**Issue by rstoyanchev** [apollographql/federation-jvm#407]
The [following part of the usage sample](https://github.com/apollographql/federation-jvm/blob/a9a0e30192629932e23f98bb853ad782696a819d/spring-subscription-callback/README.md?plain=1#L102-L124) should probably be updated like the [config in the federation-jvm-spring-example](https://github.com/apollographql/federation-jvm-spring-example/blob/main/reviews-subgraph/src/main/java/com/example/reviews/ReviewsApplication.java) to make use of the built-in support in Spring for GraphQL 1.3.

**Comment by dariuszkuc** [comment]
Thanks for raising this! I updated https://github.com/apollographql/federation-jvm/pull/404 with simplified config.
