### ISSUE TITLE
Publish a graphql-java 19 supporting Federation 2.6/2.7

### ISSUE THREAD

**Issue by theJC** [apollographql/federation-jvm#419]
### Problem:
Many of your customers are stuck on graphql-java 19 right now.  19.x dev seems to be winding down with only a couple releases this year, but is still in use by many.

With version 3.0.0 and higher, the federation-jvm library became backwards incompatible with graphql-java 19, and therefore anyone required to use 19 is stuck with older federation-jvm versions which provides directive definitions only up to the Federation 2.3 directives.

We are using Netflix DGS 5.4.X.  Spring Boot 3 is required to allow us to migrate to a version of Netflix DGS that supports graphql-java 20.  Unfortunately its going to be quite some time until our company is able to bump from Spring Boot 2.7 -> 3, and we need to leverage the use of Apollo's directives in our supergraph schema like `@policy` to be leveraged in Gateway/Router, but need to be declared on the DGS subgraph that contributes to it.

### Solution: 
I've created a branch in my fork off of 2.3.1 that I then have picked just the changes I believe were necessary to support adding support all the way up to federation 2.6/2.7.  I ignored anything else in the evolution of this library, and focused on just the bare minimum needed to get my DGS 5.4.5 services started up without it complaining about directives it doesnt understand.

https://github.com/theJC/federation-jvm/commits/v2.3.1_fed27/

Please consider pulling in this branch (or do something similar to what Ive done here - it was fairly easy) and update your project's publishing config to publish official graphql-java 19 compatible versions of this library from a 2.3.X branch that provides these directives that work in the graphql-java 19 universe,  to enable your customers to use the newer Apollo directives for those of us that are stuck on older libraries/frameworks.

**Comment by dariuszkuc** [comment]
👋 I just released [v2.4.0](https://github.com/apollographql/federation-jvm/releases/tag/v2.4.0) with latest Fed support.
