### ISSUE TITLE
Support for graphql-java 14

### ISSUE THREAD

**Issue by lennyburdette** [apollographql/federation-jvm#45]
The newest version of graphql-java was released January 16 and contains a few breaking changes. Supporting the new APIs doesn't look too complicated—to jumpstart things, here's a changeset with passing tests: https://github.com/apollographql/federation-jvm/compare/master...lennyburdette:graphql-java-14?expand=1

**Comment by paulbakker** [comment]
I should have created an issue as well, but I have an open PR to address this: https://github.com/apollographql/federation-jvm/pull/46

**Comment by glasser** [comment]
#41 also addresses this

**Comment by lennyburdette** [comment]
Closing in favor of #41 and #46
