### ISSUE TITLE
Dump AGM's graphql-java schema, `engine-kotlin`, in test fixtures

### ISSUE THREAD

**Issue by pcarrier** [apollographql/federation-jvm#55]
Mentioned in passing in https://github.com/apollographql/federation-jvm/pull/53
Looks like it'd catch bugs our simplistic schemas won't, and should take low effort to Apollo employees.

**Comment by dariuszkuc** [comment]
Cleaning up old issues. Test schemas are already used in our federation transforms (https://github.com/apollographql/federation-jvm/tree/master/graphql-java-support/src/test/resources/schemas).
