### ISSUE TITLE
Is there a hook to customize HTTP requests to downstream Gql servers?

### ISSUE THREAD

**Issue by joffrey-bion** [apollographql/federation-jvm#61]
We have a use case for which we need to pass a structured context object downstream to multiple services.
This context object cannot really be part of the graphql schema itself, because it is added by a middleware internally. It is not part of the "public" graphql schema.
Also, it is a bit too big to be passed in the headers, and it is structured, so not really a good fit either.

Is there a way to customize the HTTP requests that are sent between the federation gateway and the underlying GraphQL servers?

Something like that seems doable with the NodeJS Apollo Gateway:
https://www.apollographql.com/docs/apollo-server/federation/gateway/#customizing-requests-and-responses

**Comment by sachindshinde** [comment]
Yep, you can place the structured context object in the `extensions` property of the JSON body in HTTP GraphQL requests and responses.

The steps are as follows:
- In the gateway's server constructor, you pass in a `context` function that extracts the context object from the gateway request and adds it to the gateway context, e.g.
```typescript
const server = new ApolloServer({
  gateway: /* gateway constructor */ ,
  subscriptions: false,
  context: ({ req }) => {
    const contextObject = /* Parse the context object from req.body */ ;
    // Add the context object to the gateway context
    return { contextObject };
  },
});
```
- In the gateway constructor, you pass in a `buildService` function that creates a `RemoteGraphQLDataSource` sub-class that defines a `willSendRequest()` callback to take the context object out of the gateway context and embed it in `request.extensions` and a `didReceiveResponse()` callback to take the context object out of `response.extensions` and add it to the gateway context. This looks like:
```typescript
const server = new ApolloServer({
  gateway: new ApolloGateway({
    serviceList: /* service list */ ,
    buildService: ({ url }) => {
      return new ContextObjectDataSource({ url });
    },
  }),
  subscriptions: false,
  context: /* context function */ ,
});

class ContextObjectDataSource extends RemoteGraphQLDataSource {
  willSendRequest({ request, context }) {
    if (context.contextObject) {
      request.extensions = {
        ...request.extensions,
        contextObject: context.contextObject,
      };
    }
  }

  didReceiveResponse({ response, context }) {
    if (response.extensions && response.extensions.contextObject) {
      context.contextObject = response.extensions.contextObject;
    }
    return response;
  }
};
```
- In the implementing service's server constructor, you pass in a plugin that defines a `requestDidStart()` callback to take the context object out of `request.extensions` and add it to the implementing service context and a `willSendResponse()` callback to take the context object out of the implementing service context and embed it in `response.extensions`. This looks like:
```typescript
const server = new ApolloServer({
  schema: /* implementing service schema */ ,
  plugins: [{
    requestDidStart: ({ request, context }) => {
      if (request.extensions && request.extensions.contextObject) {
        context.contextObject = request.extensions.contextObject;
      }

      return {
        willSendResponse: ({ context, response }) => {
          response.extensions = {
            ...response.extensions,
            contextObject: context.contextObject,
          };
        },
      };
    },
  }],
});
```

**Comment by joffrey-bion** [comment]
Hi, thanks a lot for the detailed answer.

I'm sorry it was probably not clear in my question, but I had seen it was possible in the NodeJS version.

My question was about whether this was possible with this `apollofederation-jvm` project, in Java, sorry for the confusion 😥

**Comment by joffrey-bion** [comment]
Wait, maybe I got confused.

I thought this project was meant to build a federation gateway instead of the nodeJS federation gateway.
But I believe I was wrong and this is not the case. Is this project instead meant to be used for downstream GraphQL servers, just so that they expose their schema in a federation-compliant way?

**Comment by sachindshinde** [comment]
> But I believe I was wrong and this is not the case. Is this project instead meant to be used for downstream GraphQL servers, just so that they expose their schema in a federation-compliant way?

Yep, that's exactly right, it's a thin layer around `graphql-java` to make it federation-compliant.

> If this is the case, then please feel free to close this issue as irrelevant.

Sounds good, I'll close out the issue. If you end up having any troubles with Apollo Gateway, feel free to file an issue on their GitHub page.
