### ISSUE TITLE
SchemaTransformer.sdl() should hide the _entities and _service fields in Query

### ISSUE THREAD

**Issue by sachindshinde** [apollographql/federation-jvm#63]
As part of making `SchemaTransformer.sdl()` a public function, we also would like to hide `_entities` and `_service` from `Query` if present. (We don't need this for our internal usage, but this is useful for users who want to print out federation-spec SDL for e.g. `npx apollo service:push`.)

**Comment by dariuszkuc** [comment]
Closing as obsolete. Federation v2 no longer requires excluding federation types from the SDL.
