### ISSUE TITLE
seems very complicated compared to the spring boot graphql

### ISSUE THREAD

**Issue by xenoterracide** [apollographql/federation-jvm#65]
https://github.com/apollographql/federation-jvm/blob/master/spring-example/src/main/java/com/apollographql/federation/springexample/InventorySchemaProvider.java

why is all this needed when the spring boot graphql module loads your `.graphqls` files out of the box and maps them to components, I could be wrong, but I suspect that a cleaner, magicker layer that integrates better could be provided.

**Comment by dariuszkuc** [comment]
Hello 👋 
Libraries provided as part of `federation-jvm` project are a low level libraries for transforming GraphQL schemas to make them federation compatible. Higher level frameworks/libraries would abstract away the low level logic and provide simpler integrations. This is exactly the same behavior as with `graphql-java` and higher level frameworks like Spring GraphQL, Netflix DGS or GraphQL Java Kickstart.

Checkout below projects for example Federation JVM integrations

* [Spring GraphQL Federation Example](https://github.com/apollographql/federation-jvm-spring-example)
* [Netflix DGS Federation Example](https://github.com/Netflix/dgs-federation-example)
* [GraphQL Java Kickstart Federation Example](https://github.com/setchy/graphql-java-kickstart-federation-example)
