### ISSUE TITLE
Incompatible with graphql-java v15

### ISSUE THREAD

**Issue by hrkfdn** [apollographql/federation-jvm#66]
With the release of graphql-java 15, the `enforceSchemaDirectives` flag in `SchemaGenerator.Options` was removed (see also https://github.com/graphql-java/graphql-java/pull/1773).

This causes compilation errors, i.e. here https://github.com/apollographql/federation-jvm/blob/8894ce9a036b79f172011a158d4c719cc940e2e9/graphql-java-support/src/main/java/com/apollographql/federation/graphqljava/Federation.java#L18-L19

**Comment by sachindshinde** [comment]
Thanks for noting the options changes! We've released support for graphql-java v15 with v0.5.0.
