### ISSUE TITLE
Having issues with post request with headers to the backend spring boot graphql endpoint

### ISSUE THREAD

**Issue by kalpesh6641** [apollographql/federation-jvm#68]
Currently we do have federated jvm spring boot application which takes in couple of headers and does some header validation on federated jvm spring boot application(backend) and based on that it performs some task.

But it constantly throws NPE since the headers are not getting passed to the federated jvm spring boot application(backend), Looking at my curl or postman.

<img width="938" alt="Screen Shot 2020-06-11 at 2 34 58 PM" src="https://user-images.githubusercontent.com/12885454/84431380-d444c980-abf0-11ea-991a-2452c77fbb11.png">

This is happening only with federated integration other wise with plain graphql implementation the query fetches me data back.

Looked more into details looks like the headers dont get sent back to the federated spring boot implementation.
```
020-06-11T14:29:51.218Z DEBUG ExecutionStrategy [{}]: 'c09859cf-da90-49ae-873d-c0d3607968ad', field '/getCustomerService' fetch threw exception

java.lang.NullPointerException: null
```

Can you help on this?

**Comment by setchy** [comment]
What are you using as your gateway layer?
