### ISSUE TITLE
Need support for adding `includeDirectives` Predicate in SchemaTrandformers

### ISSUE THREAD

**Issue by EXPEvgowdaks** [apollographql/federation-jvm#79]
SPQR generate the following GraphQLDirective as part of the schema printer logic `@_mappedType, @_mappedInputField and @_mappedOperation` which fails the gateway composition. There need to be support for 'includeDirectives' Predicate, so, we could remove the private directives while generating the SDL. If not, once can not easily integrate the microservices running with SPQR graphQL service via gateway

**Comment by EXPEvgowdaks** [comment]
More info: https://github.com/leangen/graphql-spqr/issues/290

**Comment by ankit-joinwal** [comment]
@sachindshinde is there going to be an enhancement in federation-jvm that allows excluding certain directives from being written to _service{sdl} ? 

Everyone is trying to make federation work with SPQR library and we all are getting stuck at this very issue eangen/graphql-spqr#290

**Comment by ankit-joinwal** [comment]
@sachindshinde  After making changes to federation-jvm library on my local to add support for this feature i am able to make federation-jvm work with SPQR. 
I will raise PR for this. This also would unblock thousands of developers around the world from using federation-jvm with SPQR.

**Comment by ankit-joinwal** [comment]
@pcarrier I am not able to push my branch which contains fix for this issue. Can you add me as a contributor ?

**Comment by sachindshinde** [comment]
@EXPEvgowdaks @ankit-joinwal 
Apologies for the delays here, I have some thoughts and questions about the use case written in https://github.com/apollographql/federation-jvm/pull/80#issuecomment-671604037

**Comment by ankit-joinwal** [comment]
@EXPEvgowdaks refer to https://github.com/apollographql/federation-jvm/pull/80 , the last solution provided by @sachindshinde makes it possible to make SPQR work with federation by defining the directive definitions in user code.

**Comment by sachindshinde** [comment]
@EXPEvgowdaks Let me know if the [solution in the comments](https://github.com/apollographql/federation-jvm/pull/80#issuecomment-673092736) doesn't work for you, if so we can reopen this issue.
