### ISSUE TITLE
Async entity DataFetcher

### ISSUE THREAD

**Issue by hfgbarrigas** [apollographql/federation-jvm#82]
Hi,

Is the following error expected? If it is, what changes are needed in order to be supported?

```
@Override
    public Object get(DataFetchingEnvironment env) {
        return env.<List<Map<String, Object>>>getArgument(_Entity.argumentName)
                .stream()
                .map(values -> {
                    if ("User".equals(values.get("__typename"))) {
                        final Object id = values.get("id");
                        if (id instanceof String) {
                            GraphQLContext context = env.getContext();
                            context.getCtx().put("__typename", "User");
                            return this.queryResolver.getUserById((String) id); // this returns a completable future
                                                                               // returning mono/flux with appropriate wrappers is the same
                        }
                    }
                    return null;
                })
                .collect(toList());
    }
```

the type resolver:

```
@Override
    public GraphQLObjectType getType(TypeResolutionEnvironment env) {
        final GraphQLContext context = env.getContext();

        String typename = (String) context.getCtx().get("__typename");

        return Optional.ofNullable(typename)
                .map(s -> env.getSchema().getObjectType(typename))
                .orElse(null);
    }
```

The following error is present when making the query :

`query { _entities(representations: [{__typename: \"User\", id: \"a\"}]) {... on User {id name}}}`

```{"errors":[{"message":"Exception while fetching data (/_entities[0]/id) : Expected source object to be an instance of 'com.hsbc.federation.users.api.domain.User' but instead got 'java.util.concurrent.CompletableFuture'","locations":[{"line":1,"column":83}],"path":["_entities",0,"id"],"extensions":{"classification":"DataFetchingException"}},{"message":"Exception while fetching data (/_entities[0]/name) : Expected source object to be an instance of 'com.hsbc.federation.users.api.domain.User' but instead got 'java.util.concurrent.CompletableFuture'","locations":[{"line":1,"column":86}],"path":["_entities",0,"name"],"extensions":{"classification":"DataFetchingException"}}],"data":{"_entities":[null]}}```

If I change the return type to a concrete instance of User, everything works as expected.

**Comment by osi** [comment]
If you change your return type from `Object` you'll see the issue.

You're returning `List<CompletableFuture<?>>`, when you need to be returning `CompletableFuture<List<?>>`

**Comment by hfgbarrigas** [comment]
Changed to: `public CompletableFuture<List<?>> get(DataFetchingEnvironment env)` and the issue persists.

**Comment by osi** [comment]
can you post more of your current state?

-- 
(peter.royal|osi)@pobox.com - http://fotap.org/~osi

**Comment by hfgbarrigas** [comment]
sure, here's a working demo to reproduce: https://github.com/hfgbarrigas/federated-graphql

**Comment by osi** [comment]
You're returning `CompletableFuture<List<CompletableFuture<?>>`. You should only have one level of future.

Your loop is building `List<CompletableFuture<?>>`, wrapping that in a `CompletableFuture` doesn't address the issue. You'll need to do what this does (without depending on the internal graphql-java code)

https://github.com/graphql-java/graphql-java/blob/3dfeae352fce4e3fd636a7227271e1b3f9536066/src/main/java/graphql/execution/Async.java#L27-L46

It's easily done with Reactor, if you use the `DataFetcherResult` box to avoid nulls. Something like

```
    @Override
    public CompletableFuture<List<DataFetcherResult<?>>> get(DataFetchingEnvironment env) {
        return Flux.fromIterable(env.<List<Map<String, Object>>>getArgument(_Entity.argumentName))
                   .flatMapSequential(values -> {
                       if ("User".equals(values.get("__typename"))) {
                           final Object id = values.get("id");
                           if (id instanceof String) {
                               GraphQLContext context = env.getContext();
                               context.getCtx().put("__typename", "User");
                               return Mono.<User>fromFuture(this.queryResolver.getUserById((String) id))
                                          .map(r -> DataFetcherResult.newResult().data(r).build())
                                   // You can use onErrorMap to put a per-field error in the DataFetcherResult
                                   ;
                           }
                       }
                       // An empty (null) result. Probably an error though...
                       return Mono.just(DataFetcherResult.newResult().build());
                   })
                   .collectList();
    }
```

**Comment by hfgbarrigas** [comment]
Thanks, worked as expected! Closing this issue

**Comment by supriyapethkar** [comment]
@hfgbarrigas I tried to run your application (https://github.com/hfgbarrigas/federated-graphql) on local and I get this error 

`{"errors":[{"message":"Exception while fetching data (/_entities[0]/id) : Expected source object to be an instance of 'com.examples.federation.users.domain.User' but instead got 'java.util.concurrent.CompletableFuture'","locations":[{"line":1,"column":83}],"path":["_entities",0,"id"],"extensions":{"classification":"DataFetchingException"}},{"message":"Exception while fetching data (/_entities[0]/name) : Expected source object to be an instance of 'com.examples.federation.users.domain.User' but instead got 'java.util.concurrent.CompletableFuture'","locations":[{"line":1,"column":86}],"path":["_entities",0,"name"],"extensions":{"classification":"DataFetchingException"}}],"data":{"_entities":[null]}}* Closing connection 0`

Any idea what could be the issue ?
