### ISSUE TITLE
Federation#ensureQueryTypeExists seems to not account for fields added through `extends`

### ISSUE THREAD

**Issue by CaffeinatedCM** [apollographql/federation-jvm#88]
I have a bunch of services that use a base library to get their basics going, and in the base library is where I combine all the schemas (some services have many). This is working fine, however after calling `Federation#transform(final TypeDefinitionRegistry typeRegistry, final RuntimeWiring runtimeWiring)` the Query type comes back empty. I tracked it down to `Federation#ensureQueryTypeExists` returning true and thus `queryTypeShouldBeEmpty` gets set to true.

It seems that the method doesn't account for fields added through extends, so for now I'm adding a randomly generated field to the Query type before calling `transform`. This fixes the problem, but it'd be better to not have to do that.

**Comment by sachindshinde** [comment]
Thanks for reporting and digging into the bug! I've released a fix in v0.6.1, let me know if you're still having trouble.
